// ListSelectionListener Example

package pizza;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import java.awt.Cursor;
import java.awt.event.ComponentEvent;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

public class Pizza_Main extends javax.swing.JFrame {

	DefaultListModel list;
	ArrayList<String> orders;

	private PizzaOrder aOrder = null;

	public Pizza_Main() {
		initComponents();
		newOrder();
		orders = new ArrayList<String>();
		list = new DefaultListModel();
	}

	private void newOrder() {
		aOrder = new PizzaOrder();
		clearItems();
	}

	private void setSubTotal() {
		lblSubTotal.setText(aOrder.getTotalCost());
	}

	private void clearItems() {
		txtFirstName.setText("");
		txtLastName.setText("");
		radLarge.setSelected(true);
		chkExtraCheese.setSelected(false);
		chkSausage.setSelected(false);
		chkHam.setSelected(false);
		txtOrderSummary.setText("");
		lblSubTotal.setText("");
		aOrder.clearOrder();
		updateTotal.setText("");
	}

	private void submitOrder() {
		StringBuilder str = new StringBuilder();

		str.append("Order submitted");
		str.append(aOrder.getOrderInformation());
		txtOrderSummary.setText(str.toString());

		list.addElement(txtFirstName.getText() + " " + txtLastName.getText());
		orders.add(aOrder.getOrderInformation());
		orderList.setModel(list);
	}

	private void setSize(PizzaOrder.PizzaSize size) {
		aOrder.setPizzaSize(size);
		setSubTotal();
	}

	private void setCheese() {
		if (chkExtraCheese.isSelected()) {
			aOrder.setCheese(true);
		} else {
			aOrder.setCheese(false);
		}
		setSubTotal();
	}

	private void setSausage() {
		if (chkSausage.isSelected()) {
			aOrder.setSausage(true);
		} else {
			aOrder.setSausage(false);
		}
		setSubTotal();
	}

	private void setHam() {
		if (chkHam.isSelected()) {
			aOrder.setHam(true);
		} else {
			aOrder.setHam(false);
		}
		setSubTotal();
	}

	private void setLastName() {
		if (aOrder != null) {
			aOrder.setLastName(txtLastName.getText());
		}
	}

	private void setFirstName() {
		if (aOrder != null) {
			aOrder.setFirstName(txtFirstName.getText());
		}
	}

	private void terminateApplication() {
		int response = JOptionPane.NO_OPTION;
		String prompt = "Do you want to quit the pizza program?";
		String title = "Quit Pizza Program";
		response = JOptionPane.showConfirmDialog(null, prompt, title, JOptionPane.OK_CANCEL_OPTION,
				JOptionPane.QUESTION_MESSAGE);
		if (response == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		grpSize = new javax.swing.ButtonGroup();
		PizzaOrderInformation = new javax.swing.JTabbedPane();
		jPanel4 = new javax.swing.JPanel();
		btnSumbitOrder = new javax.swing.JButton();
		btnExit = new javax.swing.JButton();
		lblSubTotal = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		pnlPerson = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		txtFirstName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtLastName = new javax.swing.JTextField();
		btnNew = new javax.swing.JButton();
		btnClearItems = new javax.swing.JButton();
		pnlSize = new javax.swing.JPanel();
		radSmall = new javax.swing.JRadioButton();
		radMedium = new javax.swing.JRadioButton();
		radLarge = new javax.swing.JRadioButton();
		pnlToppings = new javax.swing.JPanel();
		chkExtraCheese = new javax.swing.JCheckBox();
		chkSausage = new javax.swing.JCheckBox();
		chkHam = new javax.swing.JCheckBox();
		lblTotal = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		OrderList = new javax.swing.JLabel();
		OrderDetails = new javax.swing.JLabel();
		btnDel = new javax.swing.JButton();
		btnUpd = new javax.swing.JButton();
		updateTotal = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		orderList = new javax.swing.JList<>();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtOrderSummary = new javax.swing.JTextPane();
		lblWelcome = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		mnuFile = new javax.swing.JMenu();
		mnuExit = new javax.swing.JMenuItem();
		mnuOrder = new javax.swing.JMenu();
		mnuSubmitOrder = new javax.swing.JMenuItem();
		mnuClearItems = new javax.swing.JMenuItem();
		mnuNew = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Best Pizza Order");
		setPreferredSize(new java.awt.Dimension(600, 600));

		PizzaOrderInformation.setToolTipText("Pizza Order Information");
		PizzaOrderInformation.setName("Pizza Order Information"); // NOI18N

		btnSumbitOrder.setText("Submit Order");
		btnSumbitOrder.setToolTipText("Click to show the order total and order summary");
		btnSumbitOrder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSumbitOrderActionPerformed(evt);
			}
		});

		btnExit.setText("Exit");
		btnExit.setToolTipText("Click to exit the the Best Pizza order application");
		btnExit.setAutoscrolls(true);
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});

		lblSubTotal.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
		lblSubTotal.setForeground(new java.awt.Color(0, 0, 80));
		lblSubTotal.setText("$0");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel1.setText("Please enter your name and select your ordering options:");

		pnlPerson.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

		jLabel2.setText("First Name:");

		txtFirstName.setToolTipText("Enter your first name");
		txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				txtFirstNameFocusLost(evt);
			}
		});

		jLabel3.setText("Last Name:");

		txtLastName.setToolTipText("Enter your last name");
		txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				txtLastNameFocusLost(evt);
			}
		});

		javax.swing.GroupLayout pnlPersonLayout = new javax.swing.GroupLayout(pnlPerson);
		pnlPerson.setLayout(pnlPersonLayout);
		pnlPersonLayout.setHorizontalGroup(pnlPersonLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPersonLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtFirstName)
								.addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		pnlPersonLayout.setVerticalGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPersonLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtFirstName,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))));

		btnNew.setText("New Order");
		btnNew.setToolTipText("Clear all items and start new order");
		btnNew.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNewActionPerformed(evt);
			}
		});

		btnClearItems.setText("Clear Items");
		btnClearItems.setToolTipText("Click to clear all the order items, the order total, and order summary");
		btnClearItems.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnClearItemsActionPerformed(evt);
			}
		});

		pnlSize.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pizza Size (please select one)",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

		grpSize.add(radSmall);
		radSmall.setText("Small: $6.99 ");
		radSmall.setToolTipText("Select for small pizza at $6.99");
		radSmall.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				radSmallItemStateChanged(evt);
			}
		});

		grpSize.add(radMedium);
		radMedium.setText("Medium: $9.99  ");
		radMedium.setToolTipText("Select for medium pizza at $9.99");
		radMedium.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				radMediumItemStateChanged(evt);
			}
		});

		grpSize.add(radLarge);
		radLarge.setText(" Large:  $12.99");
		radLarge.setToolTipText("Select for large pizza at $12.99");
		radLarge.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				radLargeItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout pnlSizeLayout = new javax.swing.GroupLayout(pnlSize);
		pnlSize.setLayout(pnlSizeLayout);
		pnlSizeLayout.setHorizontalGroup(pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlSizeLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(radLarge).addComponent(radMedium).addComponent(radSmall))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		pnlSizeLayout.setVerticalGroup(pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlSizeLayout.createSequentialGroup().addComponent(radSmall)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(radMedium)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(radLarge)));

		pnlToppings.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Toppings (Select as many as you like)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11),
				new java.awt.Color(51, 51, 255))); // NOI18N

		chkExtraCheese.setText("Extra Cheese: $1.50 ");
		chkExtraCheese.setToolTipText("Select to add extra cheese for $1.50");
		chkExtraCheese.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				chkExtraCheeseItemStateChanged(evt);
			}
		});

		chkSausage.setText("Sausage: $2.25");
		chkSausage.setToolTipText("Check to add Sausage for $2.25");
		chkSausage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				chkSausageActionPerformed(evt);
			}
		});

		chkHam.setText("Ham: $2.50");
		chkHam.setToolTipText("Check to add Ham for $2.50");
		chkHam.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				chkHamItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout pnlToppingsLayout = new javax.swing.GroupLayout(pnlToppings);
		pnlToppings.setLayout(pnlToppingsLayout);
		pnlToppingsLayout.setHorizontalGroup(pnlToppingsLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlToppingsLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(chkExtraCheese).addComponent(chkSausage).addComponent(chkHam))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		pnlToppingsLayout.setVerticalGroup(pnlToppingsLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlToppingsLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(chkExtraCheese)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(chkSausage)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(chkHam)));

		lblTotal.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
		lblTotal.setForeground(new java.awt.Color(0, 0, 80));
		lblTotal.setText("Subtotal:");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(10, 10, 10)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel4Layout.createSequentialGroup()
														.addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE,
																67, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18)
														.addComponent(lblSubTotal,
																javax.swing.GroupLayout.PREFERRED_SIZE, 67,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(btnSumbitOrder,
																javax.swing.GroupLayout.PREFERRED_SIZE, 115,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(btnClearItems,
																javax.swing.GroupLayout.PREFERRED_SIZE, 112,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE,
																112, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel4Layout.createSequentialGroup().addGap(395, 395, 395)
														.addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE,
																115, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(2, 2, 2))
								.addComponent(pnlToppings, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pnlSize, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(pnlPerson, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
								.addGap(0, 55, Short.MAX_VALUE)))
						.addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pnlPerson, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pnlSize, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(1, 1, 1)
						.addComponent(pnlToppings, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTotal).addComponent(lblSubTotal).addComponent(btnSumbitOrder)
								.addComponent(btnClearItems).addComponent(btnNew))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnExit)
						.addContainerGap(39, Short.MAX_VALUE)));

		PizzaOrderInformation.addTab("Pizza Order Information", jPanel4);

		OrderList.setText("Order List");

		OrderDetails.setText("Order Details");

		btnDel.setText("Delete Order");
		btnDel.setToolTipText("Deletes the order");
		btnDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDelActionPerformed(evt);
			}
		});

		btnUpd.setText("Update Order");
		btnUpd.setToolTipText("Updates the order");
		btnUpd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUpdActionPerformed(evt);
			}
		});

		orderList.setToolTipText("Stores order data");
		jScrollPane1.setViewportView(orderList);
		orderList.getAccessibleContext().setAccessibleName("");

		jScrollPane2.setViewportView(txtOrderSummary);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(42, 42, 42)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnDel)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(btnUpd)
														.addGap(18, 18, 18).addComponent(updateTotal,
																javax.swing.GroupLayout.PREFERRED_SIZE, 111,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(60, 60, 60)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(OrderList))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(OrderDetails)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(
										jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(52, 52, 52)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(12, 12, 12)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(OrderList).addComponent(OrderDetails))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane2)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(btnDel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnUpd).addComponent(updateTotal, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(36, Short.MAX_VALUE)));

		// ListSelectionListener is what you wanted
		orderList.addListSelectionListener(new ListSelectionListener() {

			public void valueChanged(ListSelectionEvent e) {
				int sel = orderList.getSelectedIndex();
				String orderName = orders.get(sel);
				System.out.println(orderName);
			}
		});

		btnNew.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNewActionPerformed(evt);
			}
		});

		PizzaOrderInformation.addTab("Order Summary", jPanel1);

		lblWelcome.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
		lblWelcome.setForeground(new java.awt.Color(0, 0, 255));
		lblWelcome.setText("Welcome to Best Pizza!");
		lblWelcome.setName("lblWelcome"); // NOI18N

		mnuFile.setText("File");

		mnuExit.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
		mnuExit.setMnemonic('x');
		mnuExit.setText("Exit");
		mnuExit.setToolTipText("Click to exit the application");
		mnuExit.setName("mnuExit"); // NOI18N
		mnuExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuExitActionPerformed(evt);
			}
		});
		mnuFile.add(mnuExit);

		jMenuBar1.add(mnuFile);

		mnuOrder.setText("Order");

		mnuSubmitOrder.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
		mnuSubmitOrder.setMnemonic('a');
		mnuSubmitOrder.setText("Submit Order");
		mnuSubmitOrder.setToolTipText("Click to add items to order");
		mnuSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuSubmitOrderActionPerformed(evt);
			}
		});
		mnuOrder.add(mnuSubmitOrder);

		mnuClearItems.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
		mnuClearItems.setText("Clear Items");
		mnuClearItems.setToolTipText("Click to clear ordered items");
		mnuClearItems.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuClearItemsActionPerformed(evt);
			}
		});
		mnuOrder.add(mnuClearItems);

		mnuNew.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
		mnuNew.setText("New Order");
		mnuNew.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuNewActionPerformed(evt);
			}
		});
		mnuOrder.add(mnuNew);

		jMenuBar1.add(mnuOrder);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(lblWelcome).addGap(0, 0, Short.MAX_VALUE))
						.addComponent(PizzaOrderInformation))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblWelcome).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(PizzaOrderInformation, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		PizzaOrderInformation.getAccessibleContext().setAccessibleName("Pizza Order Information");
		lblWelcome.getAccessibleContext().setAccessibleName("lblWelcome");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuExitActionPerformed
		terminateApplication();
	}// GEN-LAST:event_mnuExitActionPerformed

	private void radSmallItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_radSmallItemStateChanged
		setSize(PizzaOrder.PizzaSize.Small);
	}// GEN-LAST:event_radSmallItemStateChanged

	private void radMediumItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_radMediumItemStateChanged
		setSize(PizzaOrder.PizzaSize.Medium);
	}// GEN-LAST:event_radMediumItemStateChanged

	private void radLargeItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_radLargeItemStateChanged
		setSize(PizzaOrder.PizzaSize.Large);
	}// GEN-LAST:event_radLargeItemStateChanged

	private void btnSumbitOrderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSumbitOrderActionPerformed
		submitOrder();
	}// GEN-LAST:event_btnSumbitOrderActionPerformed

	private void chkExtraCheeseItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_chkExtraCheeseItemStateChanged
		setCheese();
	}// GEN-LAST:event_chkExtraCheeseItemStateChanged

	private void chkSausageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkSausageActionPerformed
		setSausage();
	}// GEN-LAST:event_chkSausageActionPerformed

	private void chkHamItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_chkHamItemStateChanged
		setHam();
	}// GEN-LAST:event_chkHamItemStateChanged

	private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtFirstNameFocusLost
		setFirstName();
	}// GEN-LAST:event_txtFirstNameFocusLost

	private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtLastNameFocusLost
		setLastName();
	}// GEN-LAST:event_txtLastNameFocusLost

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
		terminateApplication();
	}// GEN-LAST:event_btnExitActionPerformed

	private void btnClearItemsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearItemsActionPerformed
		clearItems();
	}// GEN-LAST:event_btnClearItemsActionPerformed

	private void mnuClearItemsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuClearItemsActionPerformed
		clearItems();
	}// GEN-LAST:event_mnuClearItemsActionPerformed

	private void mnuSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuSubmitOrderActionPerformed
		submitOrder();
	}// GEN-LAST:event_mnuSubmitOrderActionPerformed

	private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNewActionPerformed
		newOrder();
	}// GEN-LAST:event_btnNewActionPerformed

	private void mnuNewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuNewActionPerformed
		newOrder();
	}// GEN-LAST:event_mnuNewActionPerformed

	private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDelActionPerformed
		// TODO add your handling code here:
		int index = orderList.getSelectedIndex();
		list.remove(index);
		int size = list.getSize();
		if (size == 0) {
			txtOrderSummary.setText(" ");
		} else {
			if (index == list.getSize()) {
				index--;
			}
		}

		orderList.setSelectedIndex(index);
		orderList.ensureIndexIsVisible(index);
	}// GEN-LAST:event_btnDelActionPerformed

	private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdActionPerformed
		updateTotal.setText("10");

	}// GEN-LAST:event_btnUpdActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Pizza_Main.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Pizza_Main.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Pizza_Main.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Pizza_Main.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Pizza_Main mainForm = new Pizza_Main();
				mainForm.setVisible(true);
				mainForm.setLocationRelativeTo(null);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel OrderDetails;
	private javax.swing.JLabel OrderList;
	private javax.swing.JTabbedPane PizzaOrderInformation;
	private javax.swing.JButton btnClearItems;
	private javax.swing.JButton btnDel;
	private javax.swing.JButton btnExit;
	private javax.swing.JButton btnNew;
	private javax.swing.JButton btnSumbitOrder;
	private javax.swing.JButton btnUpd;
	private javax.swing.JCheckBox chkExtraCheese;
	private javax.swing.JCheckBox chkHam;
	private javax.swing.JCheckBox chkSausage;
	private javax.swing.ButtonGroup grpSize;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lblSubTotal;
	private javax.swing.JLabel lblTotal;
	private javax.swing.JLabel lblWelcome;
	private javax.swing.JMenuItem mnuClearItems;
	private javax.swing.JMenuItem mnuExit;
	private javax.swing.JMenu mnuFile;
	private javax.swing.JMenuItem mnuNew;
	private javax.swing.JMenu mnuOrder;
	private javax.swing.JMenuItem mnuSubmitOrder;
	private javax.swing.JList<String> orderList;
	private javax.swing.JPanel pnlPerson;
	private javax.swing.JPanel pnlSize;
	private javax.swing.JPanel pnlToppings;
	private javax.swing.JRadioButton radLarge;
	private javax.swing.JRadioButton radMedium;
	private javax.swing.JRadioButton radSmall;
	private javax.swing.JTextField txtFirstName;
	private javax.swing.JTextField txtLastName;
	private javax.swing.JTextPane txtOrderSummary;
	private javax.swing.JTextField updateTotal;
	// End of variables declaration//GEN-END:variables
}